"""Git operations for the documentation pipeline.

Handles branch creation, doc commits, push, and PR creation
for the OpenClaw workflow.
"""

from __future__ import annotations

import hashlib
import subprocess
from datetime import UTC, datetime
from typing import TYPE_CHECKING

import httpx

if TYPE_CHECKING:
    from pathlib import Path

from octoauthor.core.logging import get_logger

logger = get_logger(__name__)

_API_BASE = "https://api.github.com"


class GitOps:
    """Git + GitHub operations for the doc pipeline."""

    def __init__(self, repo: str, token: str, branch_prefix: str = "openclaw/doc-update") -> None:
        self.repo = repo  # e.g. "Turn10Innovations/octoauthor-test"
        self.token = token
        self.branch_prefix = branch_prefix
        self._headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github.v3+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        self.branch_name: str = ""
        self.work_dir: Path | None = None

    def generate_branch_name(self) -> str:
        """Generate a unique branch name: openclaw/doc-update-2026-03-05-a1b2c3."""
        now = datetime.now(tz=UTC)
        date_str = now.strftime("%Y-%m-%d")
        hash_str = hashlib.sha256(now.isoformat().encode()).hexdigest()[:6]
        self.branch_name = f"{self.branch_prefix}-{date_str}-{hash_str}"
        return self.branch_name

    def clone_sparse(self, target_dir: Path, base_branch: str = "main") -> Path:
        """Sparse clone — only checkout docs/ folder to minimize bandwidth."""
        self.work_dir = target_dir / self.repo.split("/")[-1]
        if self.work_dir.exists():
            # Clean up previous run
            subprocess.run(["rm", "-rf", str(self.work_dir)], check=True)

        clone_url = f"https://x-access-token:{self.token}@github.com/{self.repo}.git"

        # Sparse clone with only docs/ folder
        subprocess.run(
            ["git", "clone", "--depth", "1", "--filter=blob:none",
             "--sparse", "-b", base_branch, clone_url, str(self.work_dir)],
            check=True, capture_output=True, text=True,
        )
        subprocess.run(
            ["git", "sparse-checkout", "set", "docs"],
            cwd=self.work_dir, check=True, capture_output=True, text=True,
        )
        logger.info("Sparse clone complete", extra={"dir": str(self.work_dir)})
        return self.work_dir

    def create_branch(self) -> None:
        """Create and checkout the openclaw branch."""
        if not self.work_dir:
            msg = "Must clone first"
            raise RuntimeError(msg)
        if not self.branch_name:
            self.generate_branch_name()

        subprocess.run(
            ["git", "checkout", "-b", self.branch_name],
            cwd=self.work_dir, check=True, capture_output=True, text=True,
        )
        logger.info("Branch created", extra={"branch": self.branch_name})

    def commit_docs(self, doc_dir: Path, message: str | None = None) -> int:
        """Copy generated docs into the work tree and commit.

        Returns the number of files committed.
        """
        if not self.work_dir:
            msg = "Must clone first"
            raise RuntimeError(msg)

        # Ensure docs/user-guide exists in work tree
        dest = self.work_dir / "docs" / "user-guide"
        dest.mkdir(parents=True, exist_ok=True)
        assets_dest = dest / "assets"
        assets_dest.mkdir(parents=True, exist_ok=True)

        # Copy markdown files
        file_count = 0
        for md_file in doc_dir.glob("*.md"):
            (dest / md_file.name).write_bytes(md_file.read_bytes())
            file_count += 1

        # Copy asset files
        src_assets = doc_dir / "assets"
        if src_assets.exists():
            for asset in src_assets.iterdir():
                if asset.is_file():
                    (assets_dest / asset.name).write_bytes(asset.read_bytes())
                    file_count += 1

        # Stage and commit
        subprocess.run(
            ["git", "add", "docs/"],
            cwd=self.work_dir, check=True, capture_output=True, text=True,
        )

        commit_msg = message or (
            f"docs: auto-generate user guides ({file_count} files)\n\n"
            f"Generated by OctoAuthor (OpenClaw pipeline)\n"
            f"Branch: {self.branch_name}"
        )
        subprocess.run(
            ["git", "-c", "user.name=Arthur (OctoAuthor)",
             "-c", "user.email=arthur@octoauthor.com",
             "commit", "-m", commit_msg],
            cwd=self.work_dir, check=True, capture_output=True, text=True,
        )
        logger.info("Docs committed", extra={"files": file_count})
        return file_count

    def push(self) -> None:
        """Push the branch to origin."""
        if not self.work_dir:
            msg = "Must clone first"
            raise RuntimeError(msg)

        subprocess.run(
            ["git", "push", "-u", "origin", self.branch_name],
            cwd=self.work_dir, check=True, capture_output=True, text=True,
        )
        logger.info("Branch pushed", extra={"branch": self.branch_name})

    async def create_pr(self, title: str | None = None, body: str | None = None) -> str:
        """Create a PR on GitHub. Returns the PR URL."""
        pr_title = title or f"docs: auto-generated user guides ({self.branch_name})"
        pr_body = body or (
            "## Auto-Generated Documentation\n\n"
            "This PR contains user guides generated by **OctoAuthor** (Arthur).\n\n"
            "### What's included\n"
            "- Step-by-step markdown guides with screenshots\n"
            "- Highlighted UI elements with numbered badges\n"
            "- Zoomed PIP insets for key interactions\n\n"
            "### Review checklist\n"
            "- [ ] Screenshots match the current UI\n"
            "- [ ] Step text accurately describes each action\n"
            "- [ ] No sensitive data in screenshots\n"
            "- [ ] Guides follow the documentation standard\n\n"
            f"*Generated by OctoAuthor on branch `{self.branch_name}`*"
        )

        async with httpx.AsyncClient(headers=self._headers) as client:
            resp = await client.post(
                f"{_API_BASE}/repos/{self.repo}/pulls",
                json={
                    "title": pr_title,
                    "body": pr_body,
                    "head": self.branch_name,
                    "base": "main",
                },
            )
            resp.raise_for_status()
            pr_data = resp.json()

        pr_url = pr_data["html_url"]
        logger.info("PR created", extra={"url": pr_url, "number": pr_data["number"]})
        return pr_url
